theme: jekyll-theme-architect
repository: dco-unesp-bauru/tcc-bcc-2021-2
title: [TCCs de BCC]
description: [Trabalhos de Conclusão de Curso em Bach. em Ciência da Computação da Unesp de Bauru (FC) - 2021 2º semestre]
baseurl: /tcc-bcc-2021-2
gems: ['jekyll-github-metadata']
google_analytics: UA-92166189-1
